### ISSUE TITLE
Fix carousel on main page

### ISSUE THREAD

**Issue by SwampertSupport** [NEU-DSG/dailp-encoding#110]
@loafofpiecrust @GracefulLemming carousel needs to be up and running by June 1 for grant purposes

**Comment by loafofpiecrust** [comment]
Thanks for making this issue, I'll get on it soon. Btw I'm a fan of your new username @SwampertSupport

**Comment by loafofpiecrust** [comment]
Replaced the WordPress carousel with a React one that should be more stable.
