### ISSUE TITLE
Use Yale IIIF server for manuscript images

### ISSUE THREAD

**Issue by loafofpiecrust** [NEU-DSG/dailp-encoding#83]
Instead of using a plain URL for document images, we should allow the use of a IIIF identifier. Yale has open access to their image server, meaning we can start messing around with it.

Their URLs appear to be structured like so:

```
https://collections.library.yale.edu/iiif/2/${document_oid}/${geometry}/${size}/${rotation_degrees}/default.jpg
```

The following example pulls a small section from the first page of EFN1:

```
https://collections.library.yale.edu/iiif/2/15492122/100,100,300,300/max/0/default.jpg
```

This URL format is standard across all of their documents, so we can associate each document with the OIDs (i.e. `15492122` for EFN1) and an indicator of source (i.e. Yale = `https://collections.library.yale.edu/iiif/2/`). From there, the front-end will be able to request any portion of the image at any resolution or rotation.

**Comment by rchavez-neu** [comment]
All IIIF version 2 APIs (our included) conform to the following API documentation (uselss the IIIF server has been modified in some way): https://iiif.io/api/image/2.1/

**Comment by rchavez-neu** [comment]
The IIIF version 2 API spec documentation outlines all available parameters and functionality

**Comment by loafofpiecrust** [comment]
This was completed in 8e1326f78a9fad1d8790292c1f4719e1e91bb465 and subsequent changes to the metadata of each document. Now, we are directly using Yale's IIIF API to associate images with documents. This approach should support multiple sources, but I've only tested Yale's so far.
