### ISSUE TITLE
Workflow and markup for importing segmented audio

### ISSUE THREAD

**Issue by loafofpiecrust** [NEU-DSG/dailp-encoding#98]
How should we denote segmentation of document reading audio files to import into the database to connect to annotated/translated paragraphs?

**Comment by GracefulLemming** [comment]
Ref: https://www.fon.hum.uva.nl/praat/manual/TextGrid_file_formats.html
My current thoughts are that while using Praat for audio, we would have to use their funky format for encoding audio segmentation. Not exactly ideal... A strong alternative should be able to use a more general markup format (or export to one) and allow easy alternation between listening and markup to keep the process somewhat streamlined.

**Comment by loafofpiecrust** [comment]
This is captured on Jira/Trello and largely finished already
